-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 23:17:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webapp` DEFAULT CHARACTER SET utf8 ;
USE `webapp` ;

-- -----------------------------------------------------
-- Table `webapp`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`user` ;

CREATE TABLE IF NOT EXISTS `webapp`.`user` (
  `iduser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `is_owner` TINYINT(1) NOT NULL DEFAULT 0,
  `token` VARCHAR(255) NULL,
  `token_refresh` VARCHAR(255) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webapp`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `webapp`.`restaurant` (
  `idrestaurant` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `opening_hours` VARCHAR(45) NULL,
  `image_path` VARCHAR(100) NULL,
  `restaurant_type` TINYINT(1) NULL,
  `price_level` TINYINT(1) NOT NULL,
  `user_iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idrestaurant`),
  UNIQUE INDEX `idrestaurant_UNIQUE` (`idrestaurant` ASC) VISIBLE,
  INDEX `fk_restaurant_user_id_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_user_id`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `webapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webapp`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`item` ;

CREATE TABLE IF NOT EXISTS `webapp`.`item` (
  `iditem` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `image_path` VARCHAR(100) NULL,
  `category` VARCHAR(45) NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`iditem`),
  UNIQUE INDEX `iditem_UNIQUE` (`iditem` ASC) VISIBLE,
  INDEX `fk_item_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `webapp`.`restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webapp`.`order_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`order_history` ;

CREATE TABLE IF NOT EXISTS `webapp`.`order_history` (
  `idorder_history` INT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT NOW(),
  `total` FLOAT NOT NULL,
  `restaurant_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idorder_history`),
  UNIQUE INDEX `idorder_history_UNIQUE` (`idorder_history` ASC) VISIBLE,
  INDEX `fk_order_history_restaurant_id_idx` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_history_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `webapp`.`restaurant` (`idrestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webapp`.`order_history_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`order_history_item` ;

CREATE TABLE IF NOT EXISTS `webapp`.`order_history_item` (
  `idorder` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `price` FLOAT NOT NULL,
  `category` VARCHAR(45) NULL,
  `order_history_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idorder`),
  UNIQUE INDEX `idorder_history_item_UNIQUE` (`idorder` ASC) VISIBLE,
  INDEX `ffk_order_history_item_order_history_id_idx` (`order_history_id` ASC) VISIBLE,
  CONSTRAINT `ffk_order_history_item_order_history_id`
    FOREIGN KEY (`order_history_id`)
    REFERENCES `webapp`.`order_history` (`idorder_history`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webapp`.`shopping_cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`shopping_cart` ;

CREATE TABLE IF NOT EXISTS `webapp`.`shopping_cart` (
  `idshopping_cart` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idshopping_cart`),
  UNIQUE INDEX `idshopping_cart_UNIQUE` (`idshopping_cart` ASC) VISIBLE,
  INDEX `fk_shopping_cart_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `webapp`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webapp`.`shopping_cart_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `webapp`.`shopping_cart_item` ;

CREATE TABLE IF NOT EXISTS `webapp`.`shopping_cart_item` (
  `idshopping_cart_item` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idshopping_cart_item`),
  UNIQUE INDEX `idshopping_cart_item_UNIQUE` (`idshopping_cart_item` ASC) VISIBLE,
  INDEX `fk_shopping_cart_item_item_id_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_cart_item_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `webapp`.`item` (`iditem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
